sudo: required
services:
    - docker

before_install:
    - docker build -t samueleksmo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true samueleksmo/react-test npm test

after_success:
    - docker build -t samueleksmo/multi-client ./client
    - docker build -t samueleksmo/multi-nginx ./nginx
    - docker build -t samueleksmo/multi-server ./server
    - docker build -t samueleksmo/multi-worker ./worker
    #Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push samueleksmo/multi-client
    - docker push samueleksmo/multi-nginx
    - docker push samueleksmo/multi-server
    - docker push samueleksmo/multi-worker